name: flutter_splash_test1
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

#--------------------Packages-------------------#
dependencies:
  flutter:
    sdk: flutter

  #utility packages
  http: ^1.3.0
  intl: ^0.19.0
  logger: ^2.5.0
  lottie: ^3.2.0
  shimmer: ^3.0.0
  url_launcher: ^6.3.1
  image_picker: ^1.1.2
  cached_network_image: ^3.4.1
  flutter_native_splash: ^2.4.4
  connectivity_plus: ^6.1.2
  smooth_page_indicator: ^1.2.0+3
  carousel_slider: ^5.0.0
  flutter_dotenv: ^5.2.1
  file_picker: ^8.3.1

  #Icons
  cupertino_icons: ^1.0.8
  iconsax: ^0.0.8

  #state Management
  get: ^4.6.6
  get_storage: ^2.1.1

  # Product Specific
  readmore: ^3.0.0

  # Product Specific
  flutter_translate: ^4.1.0
  page_transition: ^2.1.0
  simple_animations: ^5.0.2
  flutter_rating_bar: ^4.0.1

  # Firebase
  firebase_core: ^3.10.1
  firebase_auth: ^5.4.1
  firebase_storage: ^12.4.1
  cloud_firestore: ^5.6.2
  google_sign_in: ^6.2.2



#------------------------ ./ Packages End ---------------------#
dev_dependencies:

  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true


#-------------------- Local Assets ------------------------#
  assets:
    - assets/images/on_boarding_images/
    - assets/images/animations/
    - assets/icons/categories/
    - assets/images/banners/
    - assets/images/products/
    - assets/images/user/
    - assets/icons/payment_methods/
    - assets/images/reviews/
    - assets/logos/
    - .env

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-MediumItalic.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 800
