name: flutter_splash_test1
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

#--------------------Packages-------------------#
dependencies:
  flutter:
    sdk: flutter

  #utility packages
  http: ^1.2.2
  intl: ^0.19.0
  logger: ^2.5.0
  url_launcher: ^6.3.1
  flutter_native_splash: ^2.4.4
  smooth_page_indicator: ^1.2.0+3

  #Icons
  cupertino_icons: ^1.0.8
  iconsax: ^0.0.8

  #state Management
  get: ^4.6.6
  get_storage: ^2.1.1

  # Product Specific
  flutter_translate: ^4.1.0
  page_transition: ^2.1.0
  simple_animations: ^5.0.2



#------------------------ ./ Packages End ---------------------#
dev_dependencies:

  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true


#-------------------- Local Assets ------------------------#
  assets:
    - assets/images/on_boarding_images/
    - assets/images/animations/
    - assets/icons/
    - assets/logos/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-MediumItalic.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 800
