// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBg2WVaBwrpp6i2JQqoctq4PNIHEvVEhV0',
    appId: '1:23269114443:web:a37bd9027a617c39aa03ce',
    messagingSenderId: '23269114443',
    projectId: 'e-commerce-app-74d6c',
    authDomain: 'e-commerce-app-74d6c.firebaseapp.com',
    storageBucket: 'e-commerce-app-74d6c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCsf8wytMOYfR3NzMGKBVaAwu5LO4aIq90',
    appId: '1:23269114443:android:8a53a35d5885ba6baa03ce',
    messagingSenderId: '23269114443',
    projectId: 'e-commerce-app-74d6c',
    storageBucket: 'e-commerce-app-74d6c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBH6uksVC6GWTfx4vPinXdPYWqHpF0qyxA',
    appId: '1:23269114443:ios:6b06fdd41d171033aa03ce',
    messagingSenderId: '23269114443',
    projectId: 'e-commerce-app-74d6c',
    storageBucket: 'e-commerce-app-74d6c.firebasestorage.app',
    androidClientId: '23269114443-rlrs7st0c6ijscuhvq8msjval8aofs1h.apps.googleusercontent.com',
    iosClientId: '23269114443-euqqvg6f1kolr07a12pge6bekukq820i.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterSplashTest1',
  );

}